### ISSUE TITLE
Why require CloseChannel() to be called twice?

### ISSUE THREAD

**Issue by chafey** [mattdf/payment-channel#7]
What is the rationale behind requiring CloseChannel() to be called twice (once with Bob's signature and once with Alice's signature)?  Alice should be responsible for closing the channel so she would be the one to call CloseChannel() twice and pay the transaction fees.  Why not have CloseChannel() take both signatures so it can be closed with one transaction?  This would be clearer, cheaper and faster.  I can't think of any advantage to having two transactions be required.

**Comment by erikdubbelboer** [comment]
Because if Bob can't close the channel to get his payment Alice can just wait for the channel to time out, call `ChannelTimeout`, and get all her money back.

Keep in mind that it will be Bob to call `CloseChannel` with both signatures. Alice signs a message with how much she wants to transfer to Bob and gives this signature to Bob. Then Bob can call `CloseChannel` for both this signature and a signature he makes by signing the same amount. Or Bob could wait for another time Alice needs to pay him and make her sign the new total amount. This way Bob can accept payments from Alice without having to do on chain transactions.

If only the signature of Alice was required to close the chanel Alice could sign a 0 amount and call `CloseChannel` herself so Bob doesn't get anything. Or if only the signature of Bob was required he could immediately call `CloseChannel` and transfer everything to himself without any input from Alice.

**Comment by chafey** [comment]
My comment was from the perspective of Bob paying Alice as is described in the [blog post corresponding to this repo](https://medium.com/@matthewdif/ethereum-payment-channel-in-50-lines-of-code-a94fad2704bc).  You responded from the perspective of Alice paying Bob which is confusing.  To avoid further confusion, I suggest we continue this thread from the perspective of Bob paying Alice.

To clarify my question, I want to know why CloseChannel() doesn't take the signatures from both Bob and Alice as input parameters so it can be called exactly once to close the channel.  It seems like the most common use case is when Alice wants a payout and that requires CloseChannel() to be called twice - once with Bob's sig and once with Alice's.  For this use case, it would make more sense if Alice could just call CloseChannel() once with both sigs to close it out.  Does anyone know why CloseChannel() was not designed this way?

**Comment by erikdubbelboer** [comment]
Sorry for the confusion. I agree `CloseChannel` could easily be designed to have both signatures as argument. Not sure why it's not. But I guess you can still do both function calls in one transaction.

**Comment by chafey** [comment]
OK - thanks for the response!  I just wanted to make sure I was understanding this properly and not missing some side use cases.
